### ISSUE TITLE
clang-3.8 -no-canonical-prefixes hello.c

### ISSUE THREAD

**Issue by songyunqi123** [ubuntudesign/cn.ubuntu.com#113]
## Summary
clang-3.8: error: unable to execute command: Executable "clang-3.8" doesn't exist!
[please describe the issue]
when I use the "clang-3.8 -no-canonical-prefixes hello.c",then report "clang-3.8: error: unable to execute command: Executable "clang-3.8" doesn't exist!".
But,when I use "/usr/bin/clang-3.8 -no-canonical-prefixes hello.c",it's OK!
## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by deadlight** [comment]
This is the repository for the cn.ubuntu.com website; you need to file a bug against the specific package you're having issues with.

Apologies for the confusion,
Karl
