### ISSUE TITLE
Removing old article on China site (cn.ubuntu.com)

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/cn.ubuntu.com#117]
## Summary

Need to remove the following article on cn.ubuntu.com news section, as 
- we no longer using 友邦拓 as the Chinese name of Ubuntu in China, it is causing confusion
- another company in China is claiming they own the copyright of this term, and might take legal action on the usage of this term. 

## Process
removing the last article on this page: http://cn.ubuntu.com/news/, it is an external vidoe link to youku.com

## Screenshot
![image](https://cloud.githubusercontent.com/assets/19166875/21310957/c125474c-c5dc-11e6-8c3c-73200032d307.png)

**Comment by deadlight** [comment]
@Apeshere I'm removing this today. I'll let you know when the change is live.
