### ISSUE TITLE
when I boot my computer there comes a bug.

### ISSUE THREAD

**Issue by fattypiggy** [ubuntudesign/cn.ubuntu.com#119]
## Summary
Error uncleared pch fifo underrun on pch transcoder A
Error PCH transcoder A FIFo underrun
sda1:clean 300971/30015488 files,4008087/120034816 blocks

I can access to my OS,but I am worried about it.I don't know what happened.
Anybody can help me to fix it?
You can send email to william_jing@qq.com,thank you very much.
## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
fattypiggy

this site is for bugs on the website, not in Ubuntu... perhaps look here? http://askubuntu.com/questions/582299/fifo-underrun-error-shown-during-booting
